### ISSUE TITLE
Running apps through websockets doesn't work in 2021 model

### ISSUE THREAD

**Issue by espilva** [xchwarze/samsung-tv-ws-api#117]
Hi, running apps calling ws doesn't work on my QN900A --2021 model. Using the rest interface successfully launch the apps.

**Comment by xchwarze** [comment]
Samsung removed the service so that it would do that. It is not clear how to determine if the TV still has the service or not.
I assumed it was because of the OS version but it is still unclear.

**Comment by espilva** [comment]
Thanks for the answer and thanks so much for the package!! 

Did Samsung offer any alternative?

**Comment by xchwarze** [comment]
samsung actually does these stupid things to prevent us from escaping from the cloud

**Comment by marksteward** [comment]
Is there any documentation on which TVs this affects? I'm seeing it with a QE32LS03BBUXXU (unknown firmware version).

The websockets API works for TV-remote operations, but starting or listing apps just does nothing (#128, #99, #30, #23). I'm coming to this from HomeAssistant where all the documentation and online discussions say it works, so it was only out of frustration that I tried this library directly!

The REST API works fine, so I'd be more than happy to update the HA code, but it'd be good to be able to say "this is how it is on all firmwares since 2021" or something.
