### ISSUE TITLE
Rest API description

### ISSUE THREAD

**Issue by raphtabe** [xchwarze/samsung-tv-ws-api#131]
Hello, 

Thank for you job, it looks amazing.

I'm trying to find documentation on the API to configure the Art Mode.
I would like to send the command my self (ws://IP:8001/api/v2/).
A basic GET works, but I don't find the documentation the rest of the API.
I try to read and understand your code, but it's difficult for me.

- Could tell me the uri and content I would need to sent to the TV for a set_artmode (as an examle).
and/or
- Do you know where to find a documentation with all the possible commands ?

Thanks in advance.

**Comment by raphtabe** [comment]
Ok, I have analyzed with Wireshark.
I can't send easy paquets to send some comments...

**Comment by xchwarze** [comment]
The problem is that there is no documentation. Everything is done with reverse over apps and other apps.
The TV runs different apps in parallel that can answer you via http and ws. ART and remote control are different apps that samsung is updating with the tiren versions (that's why things stop working when the version changes).
